#!/usr/bin/env python3
"""Generate offline English recordings with Microsoft Edge neural voices.
Run with Python + edge-tts, ffmpeg and ffprobe installed. Existing Turkish assets stay untouched.
"""
import asyncio,base64,hashlib,json,pathlib,shutil,subprocess,sys
import edge_tts
ROOT=pathlib.Path(__file__).resolve().parent.parent
KABIR=(ROOT/'src/narration.js').exists()
TEXT=ROOT/('src/narration-en-text.json' if KABIR else 'voice-en-text.json')
OUT=ROOT/('src/narration-en.js' if KABIR else 'sesler-en.js')
CACHE=ROOT/'.english-voice-cache'
FFMPEG=shutil.which('ffmpeg') or '/opt/homebrew/bin/ffmpeg'
FFPROBE=shutil.which('ffprobe') or '/opt/homebrew/bin/ffprobe'
LINES=json.loads(TEXT.read_text())
TR=json.JSONDecoder().raw_decode((ROOT/'src/narration.js').read_text().split('window.BABA.Narration = ',1)[1])[0] if KABIR else {}
TRIM='silenceremove=start_periods=1:start_threshold=-48dB:start_silence=0.035:detection=peak,areverse,silenceremove=start_periods=1:start_threshold=-48dB:start_silence=0.10:detection=peak,areverse,afade=t=in:d=0.006'
def config(key):
 if not KABIR:return 'en-GB-SoniaNeural','-3%','+1Hz',TRIM
 voice='en-US-GuyNeural' if key=='heroOath' else 'en-US-ChristopherNeural' if key=='cellat' else 'en-GB-ThomasNeural'
 # Native articulation remains intact; subtle low end and a short room tail, no robotic pitch shifting.
 return voice,'-8%','-3Hz',TRIM+',highpass=f=65,lowpass=f=8500,equalizer=f=170:t=q:w=0.8:g=2,aecho=0.8:0.88:48:0.07,alimiter=limit=0.92'
def path(key,text):
 return CACHE/(hashlib.sha256(json.dumps([text,*config(key)]).encode()).hexdigest()+'.mp3')
async def record(key,text,sem):
 p=path(key,text)
 if p.exists() and p.stat().st_size>1000:return
 async with sem:
  voice,rate,pitch,filters=config(key)
  for attempt in range(5):
   raw=p.with_suffix('.raw.mp3')
   try:
    await edge_tts.Communicate(text,voice,rate=rate,pitch=pitch).save(str(raw))
    subprocess.run([FFMPEG,'-y','-loglevel','error','-i',str(raw),'-af',filters,'-ac','1','-ar','24000','-c:a','libmp3lame','-b:a','48k',str(p)],check=True)
    raw.unlink(missing_ok=True)
    if p.stat().st_size<1000:raise RuntimeError('empty recording')
    print('recorded',key,flush=True);return
   except Exception as e:
    raw.unlink(missing_ok=True)
    if attempt==4:raise RuntimeError(f'{key}: {e}')
    await asyncio.sleep(2*(attempt+1))
async def main():
 CACHE.mkdir(exist_ok=True)
 sem=asyncio.Semaphore(3)
 await asyncio.gather(*(record(k,t,sem) for k,t in LINES.items()))
 mp3={};dur={};records={}
 for k,t in LINES.items():
  p=path(k,t);d=float(subprocess.check_output([FFPROBE,'-v','error','-show_entries','format=duration','-of','csv=p=0',str(p)],text=True).strip())
  if d<.25:raise RuntimeError(f'{k}: recording too short')
  b=base64.b64encode(p.read_bytes()).decode();mp3[k]=b;dur[k]=round(d,3)
  if KABIR: records[k]={'text':t,'speaker':'Bahtiyar' if k=='heroOath' else 'Chain Executioner' if k=='cellat' else 'Narrator','voice':config(k)[0],'style':TR[k]['style'],'duration':dur[k],'audio':b}
 head='// Generated by tools/gen_english_voices.py. Native English neural recordings; trimmed mono MP3, embedded for file://.\n'
 if KABIR:body='window.BABA = window.BABA || {};\nwindow.BABA.NarrationEN = '+json.dumps(records,ensure_ascii=False)+';\n'
 else:body='window.FEZA_VOICE_EN_TEXT = '+json.dumps(LINES,ensure_ascii=False)+';\nwindow.FEZA_VOICE_EN_MP3 = '+json.dumps(mp3)+';\nwindow.FEZA_VOICE_EN_DUR = '+json.dumps(dur)+';\n'
 OUT.write_text(head+body)
 print(f'WROTE {OUT.name}: {len(LINES)} lines, {sum(dur.values()):.1f}s, {OUT.stat().st_size} bytes',flush=True)
if __name__=='__main__':asyncio.run(main())
